demand_tasks:
- label:        "Walking Group"
  task:         walking_group_slow
  duration:     1800
  waypoint:     GhostKitchen
  params:       []
- label:        "Object Search"
  task:         object_search_mdp
  duration:     1800
  waypoint:     LesserCoders
  params:       
  - string:     "[asus_box, jasmine_green_tea]" 
  - string:     "[GhostKitchen, Room102, Room106Exit]"
- label:        "Object Learning"
  task:         learn_object
  duration:     600
  waypoint:     Room102
  params:       
  - string:     Room102
- label:        "Metric Map"
  task:         ptu_pan_tilt_metric_map
  duration:     600
  waypoint:     ChargingPoint
  params:       
  - int: -160
  - int: 20
  - int: 160
  - int: -30
  - int: 30
  - int: 30
- label:        "Observe"
  task:         wait_action
  duration:     1800
  waypoint:     HigherCoders
  params:       []
- label:        "Charging"
  task:         wait_action
  duration:     1800
  waypoint:     ChargingPoint
  params:       []

